version: "3.7"

services:
  couchdb:
    image: couchdb:2
    environment:
      COUCHDB_USER: couchdb
      COUCHDB_PASSWORD: couchdb
    networks:
      - artemis_network
    restart: unless-stopped
    volumes:
      - type: volume
        source: couchdb_data
        target: "/opt/couchdb/data"

  postgres:
    image: postgres:11.1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - artemis_network
    restart: unless-stopped
    volumes:
      - type: volume
        source: postgres_data
        target: "/var/lib/postgresql/data"

  server:
    build: .
    command: bin/docker-dev/entrypoint
    depends_on:
      - couchdb
      - postgres
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    networks:
      - artemis_network
    ports:
      - ${ARTEMIS_API_PORT}:${ARTEMIS_API_PORT}
      - ${ARTEMIS_WEB_PORT}:${ARTEMIS_WEB_PORT}
    restart: unless-stopped
    volumes:
      - type: bind
        source: .
        target: "/app/source"

networks:
  artemis_network:
    driver: bridge

volumes:
  couchdb_data:
  postgres_data:
