{:ok, _} = Application.ensure_all_started(:ex_machina)
Artemis.Drivers.IBMCloudant.CreateAll.call()
ExUnit.configure(exclude: [cloudant_exclusive_feature: true, pending: true])
ExUnit.start()
Artemis.Repo.GenerateData.call()
Ecto.Adapters.SQL.Sandbox.mode(Artemis.Repo, :manual)
